# Generated by Django 2.1.1 on 2018-10-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181023_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocione',
            name='Descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
