# Generated by Django 2.1.1 on 2018-11-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181122_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promocione',
            new_name='Promocion',
        ),
    ]
