# Generated by Django 2.1.1 on 2018-11-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181122_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursale',
            name='Direccion',
            field=models.CharField(max_length=250),
        ),
    ]
