# Generated by Django 2.1.1 on 2018-11-23 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181122_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursale',
            name='Ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ciudad'),
        ),
    ]
