# Generated by Django 2.1.1 on 2018-11-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181122_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=250)),
                ('Imagen', models.ImageField(upload_to='Previo')),
                ('Horario', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.RenameModel(
            old_name='Promocione',
            new_name='Promocion',
        ),
        migrations.RemoveField(
            model_name='sucursale',
            name='Ciudad',
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name': 'Promocion', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.DeleteModel(
            name='Sucursale',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='Ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ciudad'),
        ),
    ]
