# Generated by Django 2.1.3 on 2018-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181122_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocion',
            options={},
        ),
        migrations.AlterField(
            model_name='promocion',
            name='Imagen',
            field=models.CharField(max_length=150),
        ),
    ]
