# Generated by Django 2.1.3 on 2018-12-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181206_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='Imagen',
            field=models.CharField(max_length=150),
        ),
    ]
